language: python
notifications:
  email: false
python:
  - "2.7"
install:
  - "easy_install -U setuptools"
  - "pip install ."
  - "pip install -r requirements.txt"
  - "pip install -r test_requirements.txt"
script:
  - py.test tests/runtests.py --doctest-modules -v --cov duct --cov-report term-missing
after_success:
  - coveralls